name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  E2E:
    runs-on: ubuntu-latest
    concurrency:
      group: build-v8-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create React Native app
        run: npx react-native init app --version "0.71.6"
        
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Validate config
        run: npx react-native@latest init AwesomeProject
