name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  E2E:
    runs-on: macos-12
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: eeeee
        run: npx react-native@latest init AwesomeProject
